### ISSUE TITLE
Where should I start? Is there a quick start guide?

### ISSUE THREAD

**Issue by MercuryLc** [OpenCloudOS/perf-prof#2]
I used build/Documentation/Build.txt, but this is a bit difficult for me. The build was not successful. Can you provide a quick start guide? Thank you.

**Comment by duanery** [comment]
yum install -y elfutils-libelf-devel xz-devel

**Comment by MercuryLc** [comment]
Thank you for your reply. I solved the problem in my attempt.
Could you please answer this question? [issue](https://github.com/OpenCloudOS/perf-prof/issues/3)
Does the tool support this function now?
