### ISSUE TITLE
How to count the number of function call？

### ISSUE THREAD

**Issue by MercuryLc** [OpenCloudOS/perf-prof#3]
If I want to use this tool to count the number of times a function (let's say foot()) is called, which module should I use? Or, which command should I use?

**Comment by duanery** [comment]
用户态的函数吗？
可以添加uprobe在foot()入口，添加uretprobe在foot()返回地方。然后利用 ./perf-prof  multi-trace -e uprobes:foot -e uprobes:foot_ret -p pid  来测量函数的执行时间。

**Comment by MercuryLc** [comment]
Okay, thank you.
Suppose I can't modify the source code here. Currently, functions in kernel mode (such as raw_spin_lock()) are not supported, right?

**Comment by duanery** [comment]
内核模式，可以使用 kprobe，kretprobe。
https://www.kernel.org/doc/html/v4.18/trace/kprobetrace.html

**Comment by MercuryLc** [comment]
OK, I need to try it. Thank you for your help very much.
